import PDFDocument from "pdfkit";
import nodemailer from "nodemailer";
import QRCode from "qrcode";

export async function createTicket(booking) {
  const ticketCode = `BM-${booking._id.toString().slice(-6).toUpperCase()}-${Math.random().toString(16).slice(2, 6).toUpperCase()}`;
  const qrString = `BEATRIX-TICKET|${ticketCode}|${booking.movieTitle}|${booking.seats.join(",")}`;
  const qrImageDataUrl = await QRCode.toDataURL(qrString, {
    margin: 1,
    width: 280,
    color: {
      dark: "#020617",
      light: "#ffffff"
    }
  });

  return {
    ticketCode,
    qrString,
    qrImageDataUrl,
    issuedAt: new Date()
  };
}

export async function ensureTicket(booking) {
  if (booking.ticket?.ticketCode && booking.ticket?.qrImageDataUrl) {
    return booking.ticket;
  }

  booking.ticket = await createTicket(booking);
  await booking.save();
  return booking.ticket;
}

export async function createTicketPdf(booking) {
  await ensureTicket(booking);

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: "A4", margin: 50 });

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const qrBuffer = Buffer.from(booking.ticket.qrImageDataUrl.split(",")[1], "base64");

    doc
      .fillColor("#06263b")
      .roundedRect(40, 40, 515, 710, 24)
      .fill();

    doc
      .fillColor("#8cfbd2")
      .fontSize(16)
      .characterSpacing(6)
      .text("YOUR TICKET", 75, 75);

    doc
      .characterSpacing(0)
      .fillColor("#ffffff")
      .fontSize(34)
      .text(booking.movieTitle, 75, 112, { width: 290 });

    doc
      .fontSize(15)
      .fillColor("#bfdbfe")
      .text(`Ticket Code: ${booking.ticket.ticketCode}`, 75, 185)
      .text(`Seats: ${booking.seats.join(", ")}`, 75, 212)
      .text(`Cinema: ${booking.cinema}`, 75, 248)
      .text(`Showtime: ${new Date(booking.showtime).toLocaleString("en-US")}`, 75, 275)
      .text(`Total: Rp${booking.totalPrice.toLocaleString("id-ID")}`, 75, 302);

    doc
      .roundedRect(365, 72, 150, 150, 18)
      .fill("#ffffff")
      .image(qrBuffer, 379, 86, { width: 122, height: 122 });

    doc
      .moveTo(75, 360)
      .lineTo(520, 360)
      .dash(6, { space: 6 })
      .strokeColor("#7dd3fc")
      .stroke();

    doc
      .undash()
      .fontSize(13)
      .fillColor("#dbeafe")
      .text("Show this ticket QR code at the cinema entrance. This is generated by Beatrix Movie booking system.", 75, 400, {
        width: 420
      });

    doc.end();
  });
}

export async function sendTicketEmail(booking, email) {
  const pdf = await createTicketPdf(booking);
  const transporter = await createTransporter();
  const from = process.env.MAIL_FROM || '"Beatrix Movie" <tickets@beatrixmovie.test>';
  const qrBuffer = Buffer.from(booking.ticket.qrImageDataUrl.split(",")[1], "base64");

  const info = await transporter.sendMail({
    from,
    to: email,
    subject: `Your Beatrix Movie ticket - ${booking.movieTitle}`,
    text: `Your ticket ${booking.ticket.ticketCode} is ready. Seats: ${booking.seats.join(", ")}.`,
    html: `
      <div style="font-family:Arial,sans-serif;background:#06152d;color:#fff;padding:24px;border-radius:18px">
        <h1 style="margin:0 0 8px">Your Beatrix Movie Ticket</h1>
        <h2 style="margin:0 0 16px">${booking.movieTitle}</h2>
        <p><strong>Ticket Code:</strong> ${booking.ticket.ticketCode}</p>
        <p><strong>Seats:</strong> ${booking.seats.join(", ")}</p>
        <p><strong>Cinema:</strong> ${booking.cinema}</p>
        <img src="cid:ticket-qr" alt="Ticket QR" width="180" height="180" />
      </div>
    `,
    attachments: [
      {
        filename: `beatrix-ticket-${booking.ticket.ticketCode}.pdf`,
        content: pdf,
        contentType: "application/pdf"
      },
      {
        filename: "ticket-qr.png",
        content: qrBuffer,
        cid: "ticket-qr"
      }
    ]
  });

  return {
    messageId: info.messageId,
    previewUrl: nodemailer.getTestMessageUrl(info)
  };
}

async function createTransporter() {
  if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT || 587),
      secure: process.env.SMTP_SECURE === "true",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });
  }

  const testAccount = await nodemailer.createTestAccount();

  return nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
    auth: {
      user: testAccount.user,
      pass: testAccount.pass
    }
  });
}
